=== Malmo-Skyttegille-Pistolsektionen/rotation_target_frontend_webapp/public/program.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema#",
  "$id": "program.schema.json",
  "title": "Program",
  "type": "object",
  "additionalProperties": false,
  "required": [
    "id",
    "title",
    "description",
    "readonly",
    "series"
  ],
  "properties": {
    "id": {
      "type": "integer"
    },
    "title": {
      "type": "string"
    },
    "description": {
      "type": "string"
    },
    "readonly": {
      "type": "boolean"
    },
    "series": {
      "type": "array",
      "items": {
        "$ref": "#/$defs/Series"
      }
    }
  },
  "$defs": {
    "Series": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "name",
        "optional",
        "events"
      ],
      "properties": {
        "name": {
          "type": "string"
        },
        "optional": {
          "type": "boolean",
          "default": false
        },
        "events": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/Event"
          }
        }
      }
    },
    "Event": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "duration"
      ],
      "properties": {
        "duration": {
          "type": "integer",
          "description": "Duration of the event in tenths of a second. For example: 1 = 0.1s, 2 = 0.2s, ..., 10 = 1.0s"
        },
        "command": {
          "type": "string"
        },
        "audio_ids": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "List of audio IDs associated with the event."
        },
        "target_system": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "List of target system IDs associated with the event. If not specified, all target systems are affected."
        },
        "start": {
          "type": "boolean",
          "description": "Marks this event as the starting event in the series. Only one event per series may have start=true."
        }
      }
    }
  }
}

=== Malmo-Skyttegille-Pistolsektionen/rotation_target_frontend_webapp/test/data/programs/20.json
{
  "id": 20,
  "title": "Precision",
  "description": "Precision 1 + 7 ( + 3 )",
  "readonly": true,
  "series": [
    {
      "name": "Provserie",
      "optional": false,
      "events": [
        {
          "duration": 5000,
          "audio_ids": [
            50
          ]
        },
        {
          "duration": 57000,
          "audio_ids": [
            26
          ]
        },
        {
          "duration": 3000,
          "audio_ids": [
            31
          ]
        },
        {
          "duration": 297000,
          "audio_ids": [
            33
          ]
        },
        {
          "duration": 3000,
          "audio_ids": [
            35
          ]
        },
        {
          "duration": 1000,
          "audio_ids": [
            37,
            36,
            39
          ]
        }
      ]
    },
    {
      "name": "Serie 1 5min",
      "optional": false,
      "events": [
        {
          "duration": 5000,
          "audio_ids": [
            1
          ]
        },
        {
          "duration": 57000,
          "audio_ids": [
            26
          ]
        },
        {
          "duration": 3000,
          "audio_ids": [
            31
          ]
        },
        {
          "duration": 297000,
          "audio_ids": [
            33
          ]
        },
        {
          "duration": 3000,
          "audio_ids": [
            35
          ]
        },
        {
          "duration": 1000,
          "audio_ids": [
            37,
            36,
            39
          ]
        }
      ]
    },
    {
      "name": "Serie 2 5min",
      "optional": false,
      "events": [
        {
          "duration": 5000,
          "audio_ids": [
            1
          ]
        },
        {
          "duration": 57000,
          "audio_ids": [
            26
          ]
        },
        {
          "duration": 3000,
          "audio_ids": [
            31
          ]
        },
        {
          "duration": 297000,
          "audio_ids": [
            33
          ]
        },
        {
          "duration": 3000,
          "audio_ids": [
            35
          ]
        },
        {
          "duration": 1000,
          "audio_ids": [
            37,
            36,
            39
          ]
        }
      ]
    },
    {
      "name": "Serie 3 5min",
      "optional": false,
      "events": [
        {
          "duration": 5000,
          "audio_ids": [
            1
          ]
        },
        {
          "duration": 57000,
          "audio_ids": [
            26
          ]
        },
        {
          "duration": 3000,
          "audio_ids": [
            31
          ]
        },
        {
          "duration": 297000,
          "audio_ids": [
            33
          ]
        },
        {
          "duration": 3000,
          "audio_ids": [
            35
          ]
        },
        {
          "duration": 1000,
          "audio_ids": [
            37,
            36,
            39
          ]
        }
      ]
    },
    {
      "name": "Serie 4 5min",
      "optional": false,
      "events": [
        {
          "duration": 5000,
          "audio_ids": [
            1
          ]
        },
        {
          "duration": 57000,
          "audio_ids": [
            26
          ]
        },
        {
          "duration": 3000,
          "audio_ids": [
            31
          ]
        },
        {
          "duration": 297000,
          "audio_ids": [
            33
          ]
        },
        {
          "duration": 3000,
          "audio_ids": [
            35
          ]
        },
        {
          "duration": 1000,
          "audio_ids": [
            37,
            36,
            39
          ]
        }
      ]
    },
    {
      "name": "Serie 5 5min",
      "optional": false,
      "events": [
        {
          "duration": 5000,
          "audio_ids": [
            1
          ]
        },
        {
          "duration": 57000,
          "audio_ids": [
            26
          ]
        },
        {
          "duration": 3000,
          "audio_ids": [
            31
          ]
        },
        {
          "duration": 297000,
          "audio_ids": [
            33
          ]
        },
        {
          "duration": 3000,
          "audio_ids": [
            35
          ]
        },
        {
          "duration": 1000,
          "audio_ids": [
            37,
            36,
            39
          ]
        }
      ]
    },
    {
      "name": "Serie 6 5min",
      "optional": false,
      "events": [
        {
          "duration": 5000,
          "audio_ids": [
            1
          ]
        },
        {
          "duration": 57000,
          "audio_ids": [
            26
          ]
        },
        {
          "duration": 3000,
          "audio_ids": [
            31
          ]
        },
        {
          "duration": 297000,
          "audio_ids": [
            33
          ]
        },
        {
          "duration": 3000,
          "audio_ids": [
            35
          ]
        },
        {
          "duration": 1000,
          "audio_ids": [
            37,
            36,
            39
          ]
        }
      ]
    },
    {
      "name": "Serie 7 5min",
      "optional": false,
      "events": [
        {
          "duration": 5000,
          "audio_ids": [
            1
          ]
        },
        {
          "duration": 57000,
          "audio_ids": [
            26
          ]
        },
        {
          "duration": 3000,
          "audio_ids": [
            31
          ]
        },
        {
          "duration": 297000,
          "audio_ids": [
            33
          ]
        },
        {
          "duration": 3000,
          "audio_ids": [
            35
          ]
        },
        {
          "duration": 1000,
          "audio_ids": [
            37,
            36,
            39
          ]
        }
      ]
    },
    {
      "name": "Serie 8 5min",
      "optional": true,
      "events": [
        {
          "duration": 5000,
          "audio_ids": [
            1
          ]
        },
        {
          "duration": 57000,
          "audio_ids": [
            26
          ]
        },
        {
          "duration": 3000,
          "audio_ids": [
            31
          ]
        },
        {
          "duration": 297000,
          "audio_ids": [
            33
          ]
        },
        {
          "duration": 3000,
          "audio_ids": [
            35
          ]
        },
        {
          "duration": 1000,
          "audio_ids": [
            37,
            36,
            39
          ]
        }
      ]
    },
    {
      "name": "Serie 9 5min",
      "optional": true,
      "events": [
        {
          "duration": 5000,
          "audio_ids": [
            1
          ]
        },
        {
          "duration": 57000,
          "audio_ids": [
            26
          ]
        },
        {
          "duration": 3000,
          "audio_ids": [
            31
          ]
        },
        {
          "duration": 297000,
          "audio_ids": [
            33
          ]
        },
        {
          "duration": 3000,
          "audio_ids": [
            35
          ]
        },
        {
          "duration": 1000,
          "audio_ids": [
            37,
            36,
            39
          ]
        }
      ]
    },
    {
      "name": "Serie 10 5min",
      "optional": true,
      "events": [
        {
          "duration": 5000,
          "audio_ids": [
            1
          ]
        },
        {
          "duration": 57000,
          "audio_ids": [
            26
          ]
        },
        {
          "duration": 3000,
          "audio_ids": [
            31
          ]
        },
        {
          "duration": 297000,
          "audio_ids": [
            33
          ]
        },
        {
          "duration": 3000,
          "audio_ids": [
            35
          ]
        },
        {
          "duration": 1000,
          "audio_ids": [
            37,
            36,
            39
          ]
        }
      ]
    }
  ]
}

=== Malmo-Skyttegille-Pistolsektionen/rotation_target_frontend_webapp/test/data/40.json
{
    "id": 40,
    "title": "Fältträning",
    "description": "Each series starts hidden for 10s, then 3x show/hide cycles",
    "readonly": false,
    "series": [
        {
            "events": [
                {
                    "command": "hide",
                    "duration": 10000,
                    "audio_ids": [
                        1,
                        2
                    ]
                },
                {
                    "command": "show",
                    "duration": 3000
                },
                {
                    "command": "hide",
                    "duration": 3000
                },
                {
                    "command": "show",
                    "duration": 3000
                },
                {
                    "command": "hide",
                    "duration": 3000
                },
                {
                    "command": "show",
                    "duration": 3000
                },
                {
                    "command": "hide",
                    "duration": 3000
                }
            ],
            "name": "Series 1 (x=3, y=3)",
            "optional": false
        },
        {
            "events": [
                {
                    "command": "hide",
                    "duration": 10000
                },
                {
                    "command": "show",
                    "duration": 2000,
                    "audio_ids": [
                        1
                    ]
                },
                {
                    "command": "hide",
                    "duration": 3000
                },
                {
                    "command": "show",
                    "duration": 2000
                },
                {
                    "command": "hide",
                    "duration": 3000
                },
                {
                    "command": "show",
                    "duration": 2000
                },
                {
                    "command": "hide",
                    "duration": 3000
                }
            ],
            "name": "Series 2 (x=2, y=3)",
            "optional": false
        }
    ]
}
